"""enterprise_schema_extension

Revision ID: 5965b5f3c09c
Revises: ce5f9b001a69
Create Date: 2026-05-13 21:36:44.662367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5965b5f3c09c'
down_revision: Union[str, Sequence[str], None] = 'ce5f9b001a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types first (PostgreSQL does not support IF NOT EXISTS for types)
    def create_enum(name, values):
        vals = ", ".join(f"'{v}'" for v in values)
        op.execute(f"""
            DO $$ BEGIN
                CREATE TYPE {name} AS ENUM ({vals});
            EXCEPTION WHEN duplicate_object THEN null;
            END $$;
        """)

    create_enum("employmentstatusenum", ["ACTIVE", "BENCH", "NOTICE_PERIOD", "RESIGNED", "ON_LEAVE"])
    create_enum("projectstatusenum", ["PLANNING", "ONGOING", "ON_HOLD", "COMPLETED", "DELAYED", "CANCELLED"])
    create_enum("projectpriorityenum", ["LOW", "MEDIUM", "HIGH", "CRITICAL"])
    create_enum("risklevelenum", ["LOW", "MEDIUM", "HIGH"])
    create_enum("billingtypeenum", ["FIXED", "TIME_AND_MATERIAL", "RETAINER", "NON_BILLABLE"])

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.add_column('announcements', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'announcements', 'employees', ['created_by'], ['id'])
    op.add_column('employee_projects', sa.Column('allocation_percentage', sa.Float(), nullable=True))
    op.add_column('employee_projects', sa.Column('is_billable', sa.Boolean(), nullable=True))
    op.add_column('employee_projects', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('employee_projects', sa.Column('removed_at', sa.DateTime(), nullable=True))
    op.add_column('employee_projects', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('employee_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('date_of_joining', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('years_of_experience', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('work_location', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('employment_status', sa.Enum('ACTIVE', 'BENCH', 'NOTICE_PERIOD', 'RESIGNED', 'ON_LEAVE', name='employmentstatusenum'), nullable=False, server_default='ACTIVE'))
    op.add_column('employees', sa.Column('allocation_percentage', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('is_billable', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('notice_period_days', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('certifications', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('hr_notes', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.add_column('leave_requests', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('leave_requests', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('leave_requests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'leave_requests', 'employees', ['reviewed_by'], ['id'])
    op.add_column('projects', sa.Column('project_code', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('project_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.Enum('PLANNING', 'ONGOING', 'ON_HOLD', 'COMPLETED', 'DELAYED', 'CANCELLED', name='projectstatusenum'), nullable=False, server_default='PLANNING'))
    op.add_column('projects', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='projectpriorityenum'), nullable=False, server_default='MEDIUM'))
    op.add_column('projects', sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevelenum'), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('deadline', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('estimated_completion_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('actual_completion_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('budget_usd', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('actual_cost', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('billing_type', sa.Enum('FIXED', 'TIME_AND_MATERIAL', 'RETAINER', 'NON_BILLABLE', name='billingtypeenum'), nullable=True))
    op.add_column('projects', sa.Column('tech_stack', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('repo_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('environment_urls', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.add_column('tickets', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'created_at')
    op.drop_column('tickets', 'priority')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'is_archived')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'notes')
    op.drop_column('projects', 'environment_urls')
    op.drop_column('projects', 'repo_url')
    op.drop_column('projects', 'tech_stack')
    op.drop_column('projects', 'billing_type')
    op.drop_column('projects', 'actual_cost')
    op.drop_column('projects', 'estimated_cost')
    op.drop_column('projects', 'budget_usd')
    op.drop_column('projects', 'actual_completion_date')
    op.drop_column('projects', 'estimated_completion_date')
    op.drop_column('projects', 'deadline')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'risk_level')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'project_type')
    op.drop_column('projects', 'client_name')
    op.drop_column('projects', 'project_code')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'created_at')
    op.drop_column('leave_requests', 'reviewed_at')
    op.drop_column('leave_requests', 'reviewed_by')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'hr_notes')
    op.drop_column('employees', 'certifications')
    op.drop_column('employees', 'notice_period_days')
    op.drop_column('employees', 'is_billable')
    op.drop_column('employees', 'allocation_percentage')
    op.drop_column('employees', 'employment_status')
    op.drop_column('employees', 'work_location')
    op.drop_column('employees', 'years_of_experience')
    op.drop_column('employees', 'date_of_joining')
    op.drop_column('employees', 'designation')
    op.drop_column('employees', 'employee_code')
    op.drop_column('employees', 'profile_photo_url')
    op.drop_column('employees', 'date_of_birth')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'phone')
    op.drop_column('employee_projects', 'is_active')
    op.drop_column('employee_projects', 'removed_at')
    op.drop_column('employee_projects', 'assigned_at')
    op.drop_column('employee_projects', 'is_billable')
    op.drop_column('employee_projects', 'allocation_percentage')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'created_by')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
